run-kvm, bin-virt: XXX library stop
Signed-off-by: Dario Faggioli <dfaggioli@suse.com>

diff --git a/bin-virt/kvm-stop b/bin-virt/kvm-stop
--- a/bin-virt/kvm-stop
+++ b/bin-virt/kvm-stop
@@ -8,48 +8,31 @@
 # it it assumed that there will be one VM, whose name is either
 # defined in $MARVIN_KVM_DOMAIN, or it's 'marvin-mmtests'
 
-if [ "${MARVIN_KVM_DOMAIN}" = "" ]; then
-	export MARVIN_KVM_DOMAIN="marvin-mmtests"
-fi
+set -euo pipefail
 
-if [ "$1" = "--vm" ]; then
-	VMS="$2"
+basedir="$(dirname "${0}")"
+includedir="$(cd "${basedir}/.." && pwd)"
+
+# shellcheck source=shellpacks/common.sh
+source "${includedir}/shellpacks/common.sh"
+# shellcheck source=shellpacks/virt.sh
+source "${includedir}/shellpacks/virt.sh"
+
+: "${MARVIN_KVM_DOMAIN:=marvin-mmtests}"
+
+vms_csv="${MARVIN_KVM_DOMAIN}"
+
+if [[ "${1:-}" == "--vm" ]]; then
+	if [[ -z "${2:-}" ]]; then
+		echo "ERROR: --vm requires a comma-separated list of VMs." >&2
+		exit "${SHELLPACK_ERROR:--1}"
+	fi
+	vms_csv="${2}"
 	shift 2
-else
-	VMS="${MARVIN_KVM_DOMAIN}"
 fi
 
-for VM in $(tr ',' '\n' <<< "${VMS}")
-do
-	# Does virsh think it's running?
-	if ! "$(kvm-check-running "${VM}")" ; then
-		echo "Not stopping ${VM} as it is not running..."
-		continue
-	fi
-	echo "Shutting down ${VM}"
-	virsh shutdown "${VM}"
-done
+declare -a vm_array
+IFS=',' read -r -a vm_array <<< "${vms_csv}"
 
-for VM in $(tr ',' '\n' <<< "${VMS}")
-do
-	# Even if it was running before, it may be shutdown by now...
-	if ! "$(kvm-check-running "${VM}")" ; then
-		continue
-	fi
-
-	echo -n "Waiting on ${VM} shutdown to complete"
-	DURATION=0
-	while "$(kvm-check-running "${VM}")"
-	do
-		echo -n .
-		sleep 5
-
-		DURATION=$((DURATION+5))
-		if [ ${DURATION} -gt 30 ]; then
-			echo -en "\nWARNING: Normal ${VM} shutdown exceeded, destroying"
-			virsh destroy "${VM}"
-			DURATION=0
-		fi
-	done
-	echo -en "\n"
-done
+libvirt::vm_stop "${vm_array[@]}"
+exit $?
