fudifidu
Signed-off-by: Dario Faggioli <dfaggioli@suse.com>

diff --git a/bin-virt/kvm-deploy b/bin-virt/kvm-deploy
--- a/bin-virt/kvm-deploy
+++ b/bin-virt/kvm-deploy
@@ -171,6 +171,9 @@ do
 	[[ ! "$POOL" ]] && POOL="$(eval "echo \$${VM}_DISK_POOL")"
 	[[ ! "$POOL" ]] && POOL="$MMTESTS_VMS_DISK_POOL"
 	[[ ! "$POOL" ]] && POOL="default"
+	if ! check_disk_pool "$POOL" ; then
+		POOL_PATH=$(virsh pool-dumpxml "$POOL" | grep -i path | xmllint --xpath 'string(//path)' -)
+	fi
 
 	[[ "$IMPORT_DISK" ]] && IMPORT_DISK_FILE="$IMPORT_DISK"
 	[[ ! "$IMPORT_DISK_FILE" ]] && IMPORT_DISK_FILE="$(eval "echo \$${VM}_IMPORT_DISK_FILE")"
@@ -191,17 +194,27 @@ do
 	fi
 
 	if [[ "$IMPORT_DISK_FILE" ]] || [[ "$COPY_DISK_FILE" ]]; then
+		FILE="$IMPORT_DISK_FILE" ; [[ ! "$FILE" ]] && FILE="$COPY_DISK_FILE"
+		FILEN=$(echo "$FILE" | rev | cut -d'/' -f1 | rev)
+		if [[ "$FILE" =~ ^(https?|ftp)://.* ]]; then
+			if [[ ! "$POOL_PATH" ]] ; then
+				echo "ERROR: trying to use disk pool $POOL for $VM but it is not available"
+				exit -1
+			fi
+			# Download it, in the pool path, unless it's there already
+			pushd "$POOL_PATH"
+			[[ ! -f "$FILEN" ]] && wget "$FILE"
+			popd
+			if [[ ! -f "${POOL_PATH}/${FILEN}" ]]; then
+				echo "ERROR: trying to import/copy from $FILE that cannot be downloaded"
+				exit -1
+			fi
+		fi
 		if [[ "$COPY_DISK_FILE" ]]; then
 			[[ "$COPY_DISK_DEST" ]] && COPY_DISK_DEST_PATH="$COPY_DISK_DEST"
 			[[ ! "$COPY_DISK_DEST_PATH" ]] && COPY_DISK_DEST_PATH="$(eval "echo \$${VM}_COPY_DISK_DEST_PATH")"
 			[[ ! "$COPY_DISK_DEST_PATH" ]] && COPY_DISK_DEST_PATH="$MMTESTS_VMS_COPY_DISK_DEST_PATH"
-			if [[ ! "$COPY_DISK_DEST_PATH" ]]; then
-				if ! check_disk_pool "$POOL" ; then
-					echo "ERROR: requested storage pool $POOL for $VM is not available"
-					exit 1
-				fi
-				COPY_DISK_DEST_PATH=$(virsh pool-dumpxml "$POOL" | grep -i path | xmllint --xpath 'string(//path)' -)
-			fi
+			[[ ! "$COPY_DISK_DEST_PATH" ]] && COPY_DISK_DEST_PATH="$POOL_PATH"
 			COPY_DISK_DEST_FILE=$(mktemp "${COPY_DISK_DEST_PATH}/${VM}-XXXX.disk")
 			if [[ "$COPY_DISK_COW" == "true" ]]; then
 				install-depends qemu-tools
@@ -219,6 +232,9 @@ do
 			DISK_SPEC="$IMPORT_DISK_FILE"
 		fi
 		IMPORT="--import"
+		# - if fixup requested, do it, with libguestfs-&-friends
+		install-depends libguestfs
+		guestfish --rw -a "$DISK_SPEC" -i rm /etc/systemd/system/default.target.wants/jeos-firstboot.service
 	else
 		DISK_SPEC="$(eval "echo \$${VM}_DISC_SPEC")"
 		[[ ! "$DISK_SPEC" ]] && DISK_SPEC="$MMTESTS_DISK_SPEC"
@@ -231,6 +247,7 @@ do
 			DISK_SPEC="size=$DISK_FILE_SIZE,pool=$POOL"
 		fi
 		POOL=$(echo ${DISK_SPEC}|grep -o 'pool=.*'|cut -f2 -d'='|cut -f1 -d',')
+		# POOL may be different from the one we already before, so do it again
 		if ! check_disk_pool "$POOL" ; then
 			echo "ERROR: requested storage pool $POOL for $VM is not available"
 			exit 1
