kvm: create standalone scripts for checkinging if VMs are defined/running/etc
The one that checks if they're defined is extracted from kvm-define,
where it was a function.

While there, refactor kvm-check-running to look similar.

This commit introduces practically no functional change (except an
additional check in kvm-start) and is just preparatory.
for further changes.

While there, simplify (and harmonize) parameter handling in all
the scripts in bin-virt.

Signed-off-by: Dario Faggioli <dfaggioli@suse.com>

diff --git a/bin-virt/kvm-start b/bin-virt/kvm-start
--- a/bin-virt/kvm-start
+++ b/bin-virt/kvm-start
@@ -11,16 +11,18 @@ if [ "$MARVIN_KVM_DOMAIN" = "" ]; then
 	export MARVIN_KVM_DOMAIN="marvin-mmtests"
 fi
 
-if [ "$1" = "--vm" ]; then
-	VMS="$2"
-	shift 2
-else
-	VMS=$MARVIN_KVM_DOMAIN
-fi
+VMS=$MARVIN_KVM_DOMAIN
+[ "$1" = "--vm" ] && shift
+[ ! -z "$1" ] && VMS="$1"
 
 TIMEOUT=600
 for VM in $(tr ',' '\n' <<< "$VMS")
 do
+	if ! kvm-check-defined "$VM" ; then
+		echo "ERROR: cannot start $VM as it is not defined"
+		exit 1
+	fi
+
 	if kvm-check-running "$VM" ; then
 		echo $VM already running according to virsh
 		GUEST_IP=`kvm-ip-address --vm $VM 0`
